# Generated by Django 5.0.1 on 2024-02-25 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='last_edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
