# Generated by Django 5.0.1 on 2024-02-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_last_edit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='street',
            new_name='address',
        ),
    ]
