# Generated by Django 5.0.1 on 2024-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_rename_street_workshop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='city',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='phone_number',
            field=models.TextField(max_length=9),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='profession',
            field=models.TextField(max_length=100),
        ),
    ]
