# Generated by Django 5.0.1 on 2024-03-16 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb95', models.FloatField(null=True)),
                ('pb98', models.FloatField(null=True)),
                ('diesel', models.FloatField(null=True)),
                ('diesel_premium', models.FloatField(null=True)),
                ('lpg', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
