# Generated by Django 5.0.1 on 2024-03-05 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(max_length=100)),
                ('model', models.TextField(max_length=100)),
                ('prod_year', models.TextField(blank=True, max_length=100)),
                ('num_plate', models.TextField(blank=True, max_length=50)),
                ('fuel_type', models.TextField(blank=True, max_length=50)),
                ('displacement', models.FloatField(blank=True)),
                ('vin', models.TextField(blank=True, max_length=25)),
                ('favourite', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
