# Generated by Django 5.0.1 on 2024-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_brand_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='displacement',
            field=models.IntegerField(blank=True),
        ),
    ]
