# Generated by Django 5.0.1 on 2024-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_displacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='num_plate',
            field=models.TextField(max_length=50),
        ),
    ]
