# Generated by Django 5.0.1 on 2024-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='place',
            field=models.TextField(blank=True),
        ),
    ]
