# Generated by Django 5.0.1 on 2024-03-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_mileage_entry_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='notes',
            new_name='details',
        ),
    ]
