# Generated by Django 5.0.1 on 2024-03-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_entry_details_alter_entry_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='details',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
