# Generated by Django 5.0.1 on 2024-03-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_entry_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fuel_liters',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
